### PR TITLE
Possible fixes

### LINKED ISSUE #32: Add inField method
It should replace the ugly conditions in NoteVisualizer and Vision

### LINKED ISSUE #37: Code cleanup
There is currently inconsistent naming of getter methods in our code. Some are named `getValue()` and other are named `value()`. The latter is nicer, so we want to switch all of our getters to use that naming convention. You can use vscode global search to find all instances of the word "get"

Additionally, a lot of our interfaces contain unnecessary accessibility modifiers
```java
public interface Example {
    public double value();
    public String str();
}
```
These `public`s are not necessary because everything in an interface is implicitly public.

### PR DESCRIPTION
**Pull request by jonahk4**
Resolves #32 and resolves #37

### CODE REVIEW

**Review by anglesideangle — CHANGES_REQUESTED** [review]
`inField` should be a public method in `Constants.Field`, and `inConstrainedArea` shouldn't exist. `inField` should only check x and y coordinates, and the z coordinate checks should still be done in `Vision` and `NoteVisualizer`
Also, `set` in setter methods is very important. We only want to remove `get` from getter methods.

File: src/main/java/org/sciborgs1155/robot/Constants.java [hunk 1]
```diff
@@ -96,5 +97,12 @@ public static class Field {
     public static Translation3d speaker() {
       return alliance() == Alliance.Red ? RED_SPEAKER_POSE : BLUE_SPEAKER_POSE;
     }
+
```
Comment (anglesideangle) [inline src/main/java/org/sciborgs1155/robot/Constants.java:100]: this could use a line of javadoc like the other methods have

**Review by anglesideangle — CHANGES_REQUESTED** [review]
one small change

**Review by anglesideangle — APPROVED** [review]
looks good
